In [ ]:
##daily0606
'''
统计相关的函数：
np.sum：累加
np.prod：累积
np.cumsum：逐次累加
np.cumprod：逐次累积

np.mean：均值
np.var：方差
np.std：标准差

np.min：最小值
np.max：最大值
np.argmin：最小值索引
np.argmax：最大值索引

np.median：中位数
np.percentile：排序后统计值

np.any：是否存在真值的元素
np.all：所有元素是否均为真值

'''

In [25]:
import numpy as np
from np_print import print_np

ar=np.arange(1,13).reshape(4,3)
ar

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [4]:
#1.np.sum:累加

np.sum(ar)

78

In [5]:
np.sum(ar,axis=0)

array([22, 26, 30])

In [7]:
np.sum(ar[:,0])

22

In [8]:
#2.np.prod:累积
np.prod(ar)

479001600

In [9]:
np.prod(ar[0])

6

In [10]:
np.prod(ar,axis=1)

array([   6,  120,  504, 1320])

In [11]:
#3.np.cumsum：逐次累加
np.cumsum(ar)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66, 78], dtype=int32)

In [12]:
np.cumsum(ar[:,1])

array([ 2,  7, 15, 26], dtype=int32)

In [13]:
np.cumsum(ar,axis=0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18],
       [22, 26, 30]], dtype=int32)

In [14]:
#3.np.cumprod：逐次累积
np.cumprod(ar)

array([        1,         2,         6,        24,       120,       720,
            5040,     40320,    362880,   3628800,  39916800, 479001600],
      dtype=int32)

In [15]:
np.cumprod(ar[2])

array([  7,  56, 504], dtype=int32)

In [16]:
np.cumprod(ar,axis=1)

array([[   1,    2,    6],
       [   4,   20,  120],
       [   7,   56,  504],
       [  10,  110, 1320]], dtype=int32)

In [17]:
#4.np.mean：均值
np.mean(ar)

6.5

In [18]:
np.mean(ar[:,2])

7.5

In [19]:
np.mean(ar,axis=0)

array([5.5, 6.5, 7.5])

In [20]:
np.mean(ar,axis=1)

array([ 2.,  5.,  8., 11.])

In [21]:
##列中心化矩阵再对每列再取均值，每列均为0
np.mean(ar-np.mean(ar,axis=0),axis=0)

array([0., 0., 0.])

In [26]:
##行中心化矩阵
row_mean=np.mean(ar,axis=1)
print_np(row_mean)

[ 2.  5.  8. 11.] 
shape: (4,)


In [27]:
##根据广播的规则，需要在row_mean的第二维设置np.newaxis
np.mean(ar-row_mean[:,np.newaxis],axis=1)

array([0., 0., 0., 0.])

In [29]:
#5.方差与标准差
np.var(ar)

11.916666666666666

In [30]:
np.std(ar)

3.452052529534663

In [31]:
np.var(ar[0])

0.6666666666666666

In [32]:
np.var(ar,axis=1)

array([0.66666667, 0.66666667, 0.66666667, 0.66666667])

In [34]:
np.var(ar,axis=0)

array([11.25, 11.25, 11.25])

In [35]:
#6.最大最小值
np.max(ar)

12

In [36]:
np.max(ar[:,0])

10

In [37]:
np.max(ar,axis=1)

array([ 3,  6,  9, 12])

In [39]:
np.min(ar)

1

In [40]:
np.min(ar[1])

4

In [41]:
np.min(ar,axis=0)

array([1, 2, 3])

In [42]:
#7.argmin与argmax
np.argmin(ar)

0

In [43]:
np.argmin(ar[1])

0

In [45]:
np.argmin(ar,axis=1)

array([0, 0, 0, 0], dtype=int64)

In [46]:
np.argmax(ar,axis=0)

array([3, 3, 3], dtype=int64)

In [50]:
#8.中位数
np.median(ar)

6.5

In [56]:
#9.分位数
print_np(ar)
np.percentile(ar,25)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 
shape: (4, 3)


3.75