In [16]:
##daily0613

##0.关于 ndarray shape 的补充
import numpy as np
ar=np.array([1,2,3])
ar_row=np.array([[1,2,3]])
ar_col=np.array([[1],[2],[3]])
ar3d=np.array([[[1],[2],[3]],[[4],[5],[6]]])
print('ar:{}\nar_row:{}\nar_col:{}\nar3d:{}'.format(ar.shape,ar_row.shape,ar_col.shape,ar3d.shape))

ar:(3,)
ar_row:(1, 3)
ar_col:(3, 1)
ar3d:(2, 3, 1)


In [8]:
ar[:,np.newaxis].shape##加一个横轴，构成完整的二维数组

(3, 1)

In [10]:
ar[np.newaxis,:].shape##加一个竖轴，构成完整的二维数组

(1, 3)

In [11]:
ar

array([1, 2, 3])

In [12]:
ar_row

array([[1, 2, 3]])

In [13]:
ar2=ar.reshape(3,1)
ar2##同一份数据，不同的形状

array([[1],
       [2],
       [3]])

In [14]:
ar

array([1, 2, 3])

In [15]:
ar2[0]=100
ar

array([100,   2,   3])

In [17]:
##1.一维索引和切片
##>>
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
x[5]

5

In [19]:
x[:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
x[1::2]

array([1, 3, 5, 7, 9])

In [21]:
x[::-1]##逆序

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [22]:
x[5::-2]##步长为2的逆序

array([5, 3, 1])

In [23]:
x[2:3]=100 ##对切片的操作，直接影响原数据. 换言之，切片是视图，而非副本.
x

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9])

In [36]:
##2.多维索引和切片
A=np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
A[1] ##第二行

array([4, 5, 6, 7])

In [38]:
A[:,1]##第二列

array([ 1,  5,  9, 13])

In [39]:
A[1:2,1:3]=99

In [40]:
A

array([[ 0,  1,  2,  3],
       [ 4, 99, 99,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [42]:
##使用副本
B=A.copy()
B[1:2,1:3]=100

In [43]:
B

array([[  0,   1,   2,   3],
       [  4, 100, 100,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])

In [44]:
A

array([[ 0,  1,  2,  3],
       [ 4, 99, 99,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [46]:
##3.bool型索引
##先用标准正态分布生成一堆数据
X=np.random.randn(7,3)
##等价于
Y=np.random.normal(0,1,(7,3))##显式指定均值为0，方差为1的正态分布
X

array([[ 0.76966105, -0.76694534,  0.77291956],
       [-1.18904016, -0.10899054,  0.04184895],
       [ 0.40714505,  1.16440676, -1.71331459],
       [ 0.1860733 ,  1.46762725, -0.5769758 ],
       [ 2.09932859, -0.12974282, -1.1033152 ],
       [ 1.13495305, -0.24414753,  1.22275282],
       [-1.61489392, -0.71423283, -0.38120767]])

In [47]:
Y

array([[ 1.20571325,  0.79253095, -0.25369667],
       [-1.73603618, -0.83818295, -0.88349729],
       [ 0.7671061 , -0.8318801 ,  0.2735191 ],
       [ 0.61815225, -0.68130851, -0.12803605],
       [ 1.33235696, -0.52659469, -1.30601024],
       [-1.04545931, -0.31335813,  0.92501678],
       [-0.31306127,  0.43094735, -0.28911624]])

In [48]:
b=np.random.randint(1,3,(7,))##从1,2之间选择7个随机整数

In [49]:
b

array([1, 1, 2, 1, 2, 1, 1])

In [50]:
b.shape

(7,)

In [51]:
X[b==2]##选择第3行和第5行

array([[ 0.40714505,  1.16440676, -1.71331459],
       [ 2.09932859, -0.12974282, -1.1033152 ]])

In [55]:
c=np.random.randint(0,3,(3,))##从0，1，2之间随机选择3个数
c

array([2, 0, 0])

In [56]:
Y[:,c==0]##选第二列和第三列

array([[ 0.79253095, -0.25369667],
       [-0.83818295, -0.88349729],
       [-0.8318801 ,  0.2735191 ],
       [-0.68130851, -0.12803605],
       [-0.52659469, -1.30601024],
       [-0.31335813,  0.92501678],
       [ 0.43094735, -0.28911624]])

In [57]:
##4.数组索引
Z=np.arange(32).reshape(8,4)
Z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [63]:
Z[[0,2,4,6]]##选择行

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19],
       [24, 25, 26, 27]])

In [59]:
Z[[0,2,4,6]][:,1:3] ##先选择行再选择列

array([[ 1,  2],
       [ 9, 10],
       [17, 18],
       [25, 26]])

In [60]:
Z[[0,2,4,6]][:,1:3]=100 ##数组索引不会影响到原来数据.说明它返回的是副本.

In [61]:
Z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [62]:
Z[:,[0,2]]##选择列

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22],
       [24, 26],
       [28, 30]])

In [64]:
Z[:,[0,2]][0:2]##先选择列再选择行

array([[0, 2],
       [4, 6]])