In [ ]:
##daily0629
'''
一. 关系运算:
共有6个:
==: np.equal
!=: np.not_equal
<:  np.less
<=: np.less_equal
>:  np.greater
>=: np.greater_equal

1.关系运算的符号经过运算符重载，最终调用的时相应的函数. 这里和6则算术运算一样.
2.关系运算产生了bool类型的向量，其内部经过优化，使用bit位表示True与False，类似于C++的vector<bool>与bitset.
这样对bool类型的向量进行逻辑运算，不能用Python的and，or等关键字，而Python中又没有类似C++中的或且非运算符号：&&,||,! .
因此，对numpy的bool类型向量，使用位操作符 & | ~ , 来表示且，或，非.

二.逻辑运算:
|: 或
&: 且
~: 非


三.使用bool向量进行索引

'''

In [1]:
import numpy as np
##一.bool类型向量
br=np.array([0,1,1,0],dtype=np.bool)

In [4]:
br2=np.array([0,0,1,0],dtype=np.bool)

In [5]:
br and br2 ##python关键字and不支持逻辑与

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [6]:
br & br2##使用按位与实施逻辑与

array([False, False,  True, False])

In [7]:
~br

array([ True, False, False,  True])

In [8]:
br && br2 ##没有定义&&这种符号

SyntaxError: invalid syntax (<ipython-input-8-3c736876008d>, line 1)

In [9]:
##二.关系运算
ar=np.random.random(6)
ar

array([0.82679477, 0.05175064, 0.5294797 , 0.02058882, 0.80779416,
       0.35105071])

In [10]:
ar>0.5

array([ True, False,  True, False,  True, False])

In [11]:
ar2=np.arange(6).reshape(3,2)
ar2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [12]:
ar2>3

array([[False, False],
       [False, False],
       [ True,  True]])

In [13]:
ar2!=5

array([[ True,  True],
       [ True,  True],
       [ True, False]])

In [15]:
ar2==3

array([[False, False],
       [False,  True],
       [False, False]])

In [16]:
##三.逻辑计算
ar3=np.random.random((5,5))
ar3

array([[0.72075702, 0.81956834, 0.45727318, 0.32570307, 0.818354  ],
       [0.85966092, 0.77494136, 0.94561407, 0.94040828, 0.10381126],
       [0.2236874 , 0.04309442, 0.36445234, 0.67404021, 0.61232258],
       [0.54886534, 0.05209863, 0.427315  , 0.12251277, 0.59772886],
       [0.19255171, 0.26590204, 0.32836702, 0.36479846, 0.08024487]])

In [18]:
(ar3>0.4) & (ar3<0.7)

array([[False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True, False,  True, False,  True],
       [False, False, False, False, False]])

In [19]:
(ar3<0.2)|(ar3>0.8)

array([[False,  True, False, False,  True],
       [ True, False,  True,  True,  True],
       [False,  True, False, False, False],
       [False,  True, False,  True, False],
       [ True, False, False, False,  True]])

In [20]:
##四.统计，关系，逻辑的混合运算
np.sum(ar3>0.5)

11

In [22]:
np.sum(ar3>0.9,axis=0)##每行有多行个元素大于0.9

array([0, 0, 1, 1, 0])

In [23]:
np.any(ar3>0.95)

False

In [24]:
np.all(ar3<0.01)

False

In [25]:
np.all(ar3<0.11,axis=1)

array([False, False, False, False, False])

In [26]:
np.sum((ar3>0.5)&(ar3<0.6))##统计+关系+逻辑

2

In [27]:
##五.bool(数组)索引
ar3[(ar3>0.5)&(ar3<0.6)]

array([0.54886534, 0.59772886])

In [28]:
ar3[ar3<0.3]

array([0.10381126, 0.2236874 , 0.04309442, 0.05209863, 0.12251277,
       0.19255171, 0.26590204, 0.08024487])