In [28]:
##daily0614
def print_na(ar):
    '''print ndarray'''
    print(ar,"\nshape:",ar.shape)

In [29]:
##关于ndarray轴向的一些补充
import numpy as np
ar = np.array([1,2,3])
print_na(ar)

[1 2 3] 
shape: (3,)


In [32]:
ar1_3=ar[np.newaxis,:]
print_na(ar1_3)

[[1 2 3]] 
shape: (1, 3)


In [33]:
ar3_1=ar[:,np.newaxis]
print_na(ar3_1)

[[1]
 [2]
 [3]] 
shape: (3, 1)


In [35]:
##1.对于1x3矩阵增加新的轴向
ar1_1_3=ar1_3[np.newaxis,:]
print_na(ar1_3_1)##对于1x3的矩阵，尽管设置了newaxis新轴在前，但是shape仍然是1个 1x3 矩阵.

[[[1 2 3]]] 
shape: (1, 1, 3)


In [36]:
ar1_3_1=ar1_3[:,np.newaxis]
print_na(ar1_3_1)##对于1x3的矩阵，设置newaxis新轴在后，shape仍然是1个 1x3 矩阵.

[[[1 2 3]]] 
shape: (1, 1, 3)


In [38]:
##2.对于3x1矩阵增加新的轴向
ar1_3_1=ar3_1[np.newaxis,:]
print_na(ar1_3_1)##对于3x1矩阵，增加新轴在前，shape变为1个 3x1 矩阵.

[[[1]
  [2]
  [3]]] 
shape: (1, 3, 1)


In [39]:
ar3_1_1=ar3_1[:,np.newaxis]
print_na(ar3_1_1)##对于3x1 矩阵，增加新轴在后，shape变为3个 1x1 矩阵.

[[[1]]

 [[2]]

 [[3]]] 
shape: (3, 1, 1)


In [41]:
##############################
##再看看从 2维 变 3维 的情况.
ar2_3=np.arange(1,7).reshape(2,3)
print_na(ar2_3)

[[1 2 3]
 [4 5 6]] 
shape: (2, 3)


In [43]:
ar1_2_3=ar2_3[np.newaxis,:]
print_na(ar1_2_3)

[[[1 2 3]
  [4 5 6]]] 
shape: (1, 2, 3)


In [44]:
ar2_3_1=ar2_3[:,np.newaxis]
print_na(ar2_3_1)

[[[1 2 3]]

 [[4 5 6]]] 
shape: (2, 1, 3)
