In [ ]:
##daily0628
'''
广播的三个原则：
1.维数不匹配的情况下，低维向量在最左侧自动加1维
2.维数匹配但形状不匹配，轴向为1的那一维，要自动对齐另一个向量同轴的维数
3.经过1与2的调整，仍然无法匹配，广播引发异常

'''

In [6]:
import numpy as np
from np_print import print_np 


In [8]:
##1.单向广播示例
ar=np.ones((2,3))
br=np.full(2,2)
print_np(ar)

[[1. 1. 1.]
 [1. 1. 1.]] 
shape: (2, 3)


In [9]:
print_np(br)

[2 2] 
shape: (2,)


In [10]:
'''
广播时，根据规则1：br被自动扩展为(1,2)；
然后根据规则2，再扩展为(2,2),但是仍然与ar的(2,3)无法匹配，因此引起异常
'''
ar+br

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [11]:
'''
先手动把br扩展为(2,1),
再根据规则2，br又被扩展为(2,3)，与ar的形状一致，
广播生效

'''
ar+br[:,np.newaxis]

array([[3., 3., 3.],
       [3., 3., 3.]])

In [13]:
#再看不手动指定newaxis的例子
cr=np.full(3,2)
print_np(cr)

[2 2 2] 
shape: (3,)


In [14]:
'''
根据规则1:(3,)-->(1,3)
根据规则2:(1,3)-->(2,3)
与ar形状一致，广播生效
'''
ar+cr

array([[3., 3., 3.],
       [3., 3., 3.]])

In [17]:
##2.双向广播示例
a=np.arange(1,4).reshape(3,1)
print_np(a)

[[1]
 [2]
 [3]] 
shape: (3, 1)


In [16]:
b=np.full(3,3)
print_np(b)

[3 3 3] 
shape: (3,)


In [18]:
'''
1.b的维数低，先扩展为(1,3)
2.然后a,b再相互扩展：
a:(3,1)-->(3,3), b:(1,3)-->(3,3)

形状最后相同，广播生效

'''
a+b

array([[4, 4, 4],
       [5, 5, 5],
       [6, 6, 6]])

In [21]:
##3.广播应用
##广播应用最经典的实用例子当属对矩阵的中心化
X=np.random.random((10,3))##构造10x3矩阵
print_np(X)

[[0.41208279 0.04910532 0.77259735]
 [0.92826277 0.76687912 0.01472244]
 [0.6796928  0.68261173 0.76537173]
 [0.27561967 0.80958736 0.1145118 ]
 [0.69948015 0.29779016 0.31105296]
 [0.97051355 0.74185035 0.40674049]
 [0.86680915 0.96052336 0.42678276]
 [0.96754767 0.06070572 0.80508544]
 [0.63296396 0.41485173 0.16597276]
 [0.17297591 0.41866591 0.19974726]] 
shape: (10, 3)


In [22]:
X_mean=np.mean(X,axis=0)
print_np(X_mean)

[0.66059484 0.52025707 0.3982585 ] 
shape: (3,)


In [24]:
'''
X: (10,3)
X_mean:(3,)-->(1,3)-->(10,3)

'''
X_centerd=X-X_mean
print_np(X_centerd)

[[-0.24851205 -0.47115175  0.37433885]
 [ 0.26766793  0.24662205 -0.38353606]
 [ 0.01909796  0.16235465  0.36711323]
 [-0.38497517  0.28933028 -0.2837467 ]
 [ 0.03888531 -0.22246692 -0.08720554]
 [ 0.30991871  0.22159327  0.00848199]
 [ 0.2062143   0.44026628  0.02852426]
 [ 0.30695283 -0.45955136  0.40682694]
 [-0.02763089 -0.10540534 -0.23228574]
 [-0.48761893 -0.10159117 -0.19851124]] 
shape: (10, 3)


In [25]:
##在机器精度范围内，中心化矩阵再取均值，各列为0.
np.mean(X_centerd,axis=0)

array([0.00000000e+00, 1.11022302e-17, 2.22044605e-17])

In [26]:
X_centerd.mean(0)

array([0.00000000e+00, 1.11022302e-17, 2.22044605e-17])