In [ ]:
##daily0727
'''
一.各种分布的随机数生成函数

np.random.rand:  生成[0,1)上的均匀分布数据.
np.random.random:生成[0,1)上的均匀分布数据.生成矩阵时，需要指定tuple类型参数.
np.random.random_samples:等同于np.random.random

np.random.randn:生成标准正态分布数据.
np.random.randint:randint(low, high=None, size=None, dtype=’l’) ，生成low与high之间的整数.
np.random.normal: normal(loc=0.0, scale=1.0, size=None)，生成指定均值与方差的正态分布数据. 

np.random.choice:随机选取.
np.random.shuffle:就地混淆序列.
np.random.permuation:生成混淆序列.

np.arange:[start,stop)+step,  按步长输出start到stop(不含)之间的元素.
np.linspace:[start,stop]+num, 均匀采样num个start到stop（包含）之间的元素.

二.种子的作用
numpy.random.RandomState()指定种子值（指定种子值是为了使同样的条件下每次产生的随机数一样，避免程序调试时由随机数不同而引起的问题） 
如不设置种子值时,np.random.randint(8)可能产生0-7内的任意整数，且每次产生的数字可能是任意一种． 
而设置种子值后,np.random.RandomState(0).randint(8)可能产生0-7内的任意整数，但种子值不变时每次运行程序产生的数字一样．


'''

In [1]:
import numpy as np
from np_print import print_np as printn
##1.np.random.rand
x=np.random.rand(10)
printn(x)

[0.01246553 0.43175029 0.52283168 0.52972863 0.03501596 0.14756528
 0.88448535 0.41798568 0.62238126 0.89460198] 
shape: (10,)


In [2]:
X=np.random.rand(5,4)
printn(X)

[[0.4957698  0.92417543 0.48947257 0.75415644]
 [0.23871661 0.6920743  0.73608976 0.01547038]
 [0.25195932 0.66216101 0.80509568 0.04181803]
 [0.31851882 0.17955501 0.6150767  0.76564554]
 [0.02011954 0.45926524 0.40607108 0.61480524]] 
shape: (5, 4)


In [3]:
##2.np.random.random
y=np.random.random(10)
printn(y)

[0.5574606  0.67795301 0.09773728 0.81620331 0.20364669 0.63022238
 0.35942767 0.51548741 0.92553376 0.93641399] 
shape: (10,)


In [5]:
Y=np.random.random((5,4))
printn(Y)

[[0.75290906 0.63563598 0.27188335 0.97694938]
 [0.60077885 0.29884316 0.00710216 0.39248166]
 [0.2237167  0.72315007 0.50446844 0.6479009 ]
 [0.10844574 0.99539472 0.93207771 0.16985206]
 [0.80530764 0.35708101 0.98484679 0.07437299]] 
shape: (5, 4)


In [6]:
##3.np.random.randn
n=np.random.randn(10)
printn(n)

[ 1.27887667 -0.53250067  0.12670545  0.06599545  0.50531165  0.14084103
 -0.87043669 -1.80322953  0.43358645 -0.39594082] 
shape: (10,)


In [8]:
N=np.random.randn(5,4)
print(N)

[[ 0.21494681 -0.97818054 -1.40794495 -2.01905371]
 [ 1.076632   -2.02161555  1.64445742 -0.09096694]
 [ 2.40172163  1.87405746 -1.00455065  0.97713174]
 [ 1.65891629 -0.00655602  1.6672708  -0.0457173 ]
 [-0.95517073  0.04087001 -0.11649844 -1.57607637]]


In [14]:
##4.np.random.randint
for j in range(10):
    print(np.random.randint(3))##带一个参数，表示生成[0,3)之间的任意的整数. pmf为离散均匀分布.

2
2
2
2
0
2
2
1
1
2


In [15]:
i=np.random.randint(3,size=10)##生成10个[0,3)之间的任意整数. size关键字不可少.
printn(i)

[1 1 0 0 1 0 2 1 2 1] 
shape: (10,)


In [16]:
I=np.random.randint(3,size=(5,4))##将size指定为tuple，则生成矩阵.
printn(I)

[[1 2 0 2]
 [0 2 1 1]
 [2 0 1 0]
 [2 0 0 0]
 [2 1 0 2]] 
shape: (5, 4)


In [22]:
k=np.random.randint(1,3,size=10)##生成10个[1,3)之间的整数
printn(k)

[1 2 1 2 1 2 1 1 2 1] 
shape: (10,)


In [24]:
##5.np.random.normal
np.random.normal()##生成一个服从标准正态分布的数据（使用默认参数）

-0.7661507220071057

In [25]:
np.random.normal(size=(5,4))##生成服从标准正态分布的矩阵（使用默认参数）

array([[-2.15207203,  1.20585756, -1.06845912, -0.35624193],
       [ 0.60241596,  1.53460643, -0.64864322,  0.56611467],
       [ 0.96758435, -0.56948442, -0.43799211,  1.79360513],
       [-0.534262  ,  0.91258061,  0.05497629, -0.13029222],
       [ 0.11475799,  0.35726834, -0.70436856, -2.57372601]])

In [26]:
np.random.normal(100,1,size=(4,3))##生成服从均值为100，方差为1的正态分布的矩阵

array([[ 99.19803357,  99.26177949,  99.0172119 ],
       [ 99.77993885, 100.87175246,  99.05139327],
       [ 99.8576367 ,  99.77446341,  99.29486933],
       [ 99.66219349,  99.50746931,  99.61875752]])

In [29]:
##6.np.random.choice
np.random.choice(5)##等同于np.random.randint(5). 均匀分布.

2

In [30]:
np.random.choice(5,size=3)##等同于np.random.randint(5,size=3). 均匀分布.

array([4, 1, 1])

In [35]:
np.random.choice(5,8,replace=True,p=[0.1,0.2,0.3,0.4,0])##5个元素的概率质量如 p 所规定，从中有放回的抽取出8个元素.

array([1, 1, 3, 2, 1, 0, 2, 3], dtype=int64)

In [37]:
np.random.choice(5,3,replace=False,p=[0.1,0.2,0.3,0.4,0])##5个元素的概率质量如 p 所规定，从中无放回的抽取出3个元素.

array([2, 1, 3])

In [38]:
a=['a','t','t','s','e','z','e']##使用其他类型的数据源
np.random.choice(a,3)

array(['t', 't', 'e'], dtype='<U1')

In [41]:
##7.np.random.shuffle
np.random.shuffle(a)##就地混淆

In [42]:
a

['e', 's', 't', 't', 'a', 'z', 'e']

In [43]:
A=np.arange(9).reshape(3,3)
printn(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 
shape: (3, 3)


In [44]:
np.random.shuffle(A)##对矩阵的混淆只按 0 轴进行混淆

In [45]:
A

array([[6, 7, 8],
       [0, 1, 2],
       [3, 4, 5]])

In [46]:
np.random.shuffle(A,axis=1)##不可指定轴向

TypeError: shuffle() takes no keyword arguments

In [50]:
##8.np.random.permuation
np.random.permutation(a)##生成一个新的排列，不像shuffle那样进行就地混淆

array(['a', 'e', 't', 'z', 's', 'e', 't'], dtype='<U1')

In [51]:
a

['e', 's', 't', 't', 'a', 'z', 'e']

In [53]:
np.random.permutation(A)##同shuffle，只按列进行混淆

array([[3, 4, 5],
       [6, 7, 8],
       [0, 1, 2]])

In [54]:
##9.np.arange与np.linspace
np.arange(1,9)##输出[1,9)之间的元素，默认步长为1 .

array([1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
np.arange(1,9,2)##输出[1,9)之间的元素，指定步长为2 .

array([1, 3, 5, 7])

In [56]:
np.arange(9)##输出[0,9)之间的元素. 默认起始位置是0.

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [60]:
np.linspace(1,2)##均匀输出50个（默认）[1,2]之间的元素

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [61]:
np.linspace(-1,1,20)##均匀采样20个[-1,1]之间的元素.

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])