In [ ]:
##daily0612
'''
numpy的学习结构：
一.ndarray的类型以及构造
    1.ndarray定义：同构数据多维数组类型（张量）//这里参考《Python科学手册》中关于np对象与python对象的区别.
    2.ndarray的构造
    3.ndarray的属性,内部元素类型以及形状：dtype，shape，size
    4.特殊的ndarray构造函数：arange, ones, zeros, full,eye等
    
二.多维数组的轴向，索引和切片
    1.一般索引，bool型索引，数组索引;put和take
    2.一维数组切片；多维数组切片，选中指定行与列
    
三.矩阵的向量化和向量的矩阵化，矩阵的合并与切分，重复生成
    1.向量矩阵化：reshape
    2.矩阵向量化：ravel和flatten；行向量化与列向量化，C序和F序.
    3.合并：contatenate, vstack，hstack
    4.切分：split
    5.重复生成：repeat和title
    
四.广播和基础数学计算
    1.广播.
    2.与标量的运算：算术，关系，逻辑等运算. 条件表达式.
    3.扩展到多维的基础一元，二元数学运算.

五.一维向量的集合逻辑计算
    集合的并，交，差，补等计算.
    
六.线性代数
    1.向量和矩阵的转置:array.T
    2.内积：np.dot(X,Y)
    3.哈达玛积：X*Y
    4.线性方程组的解，特征值和特征向量，奇异值分解等：det行列式，inv逆阵，eig特征值，solve线性方程组的解，svd奇异值分解，lstsq最小二乘解
    
七.概率统计
    1.排序：sort
    2.各分布下随机数的生成：rand均匀分布，randn标准正态分布，binomial二项分布，normal正态分布，beta分布，uniform[0,1)之间的均匀分布，chisquare卡方分布等.
    3.统计函数：sum, mean, var, std, max, min, argmax, argmin, cumsum, cumprod等.

'''

In [62]:
##1.ndarray的基本构造
import numpy as np
ar=np.array([1,3,5,7,9])
ar_2d=np.array([[1,3,5],[2,4,6]])
ar_3d=np.array([[[1,3,5],[2,4,6]],[[7,9,11],[8,10,12]]])

In [63]:

##2.shape与reshape
##shape的类型是元组
##reshape只改变了形状，返回的仍是原始数据的引用.

ar.shape##既不是1行5列，也不是5行1列. shape的类型是只有1个元素的元组.

(5,)

In [64]:
ar_2d.shape##二维数组

(2, 3)

In [65]:
ar_3d.shape##三维数组

(2, 2, 3)

In [4]:
ar2=np.array([1,3,5,7,9])
ar2.shape==ar.shape

True

In [5]:
ar2.shape

(5,)

In [10]:
ar2.reshape(5,1).shape == ar.shape

False

In [8]:
ar2.shape

(5,)

In [11]:
t=(2,)##元组类型

In [12]:
t

(2,)

In [13]:
t=(2)##int类型

In [14]:
t

2

In [15]:
type(t)

int

In [16]:
t=(2,)
type(t)##(2)与(2,)类型就不一样，前者是int型，后者是tuple.

tuple

In [17]:
ar3=ar.reshape(5,1)##reshape只是改变了形状. ar3仍然是ar的引用，内部仍然共享数据.

In [18]:
ar3

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [19]:
ar3.shape

(5, 1)

In [20]:
ar3[0,0]=100##改变ar3的元素，ar亦随之改变

In [21]:
ar

array([100,   3,   5,   7,   9])

In [22]:
ar3

array([[100],
       [  3],
       [  5],
       [  7],
       [  9]])

In [23]:
##3.ndarray内部元素的类型以及转型操作
ar.dtype

dtype('int32')

In [24]:
ar_f=np.array([1.1,2.2,3.3,4,5])##默认浮点数使用float64
ar_f.dtype

dtype('float64')

In [25]:
ar_f32=np.array([1.1,2.2,3.3,4,5],dtype=np.float32)##指定使用float32类型的浮点数
ar_f32.dtype

dtype('float32')

In [40]:
ar_f64=ar_f32.astype(np.float64)##使用astype进行数据类型的转换，注意astype总是返回数据的副本.
ar_f64.dtype

dtype('float64')

In [41]:
ar_f64[0]=10.01##对副本的修改，不会影响原数据
ar_f64

array([10.01      ,  2.20000005,  3.29999995,  4.        ,  5.        ])

In [42]:
ar_f32

array([1.1, 2.2, 3.3, 4. , 5. ], dtype=float32)

In [43]:
##把字符串的数字转换未数值类型
ar_strnum=np.array(['1.2','3.4','5.6','7.8'])
ar_strnum.dtype

dtype('<U3')

In [45]:
ar_num=ar_strnum.astype(np.float32)

In [46]:
ar_num

array([1.2, 3.4, 5.6, 7.8], dtype=float32)

In [47]:
##4.用于构造特殊多维数组的函数

##>> np.arange
ar_1to9=np.arange(1,10)
ar_1to9

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
##>> np.ones,np.ones_like
ar_ones=np.ones([2,3])
ar_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [50]:
##>> np.zeros,np.zeros_like
ar_zeros_1d=np.zeros(6)
ar_zeros_1d.shape

(6,)

In [51]:
ar_zeros_1d

array([0., 0., 0., 0., 0., 0.])

In [54]:
 
ar_zeros_like_ar_ones=np.zeros_like(ar_ones)##这里不能使用ar_ones.shape

In [55]:
ar_zeros_like_ar_ones

array([[0., 0., 0.],
       [0., 0., 0.]])

In [56]:
ar_zeros_like_ar_ones2=np.zeros_like(ar_ones.shape)
ar_zeros_like_ar_ones2

array([0, 0])

In [58]:
##>> np.empty,np.empty_like
ar_empty_line_zeros=np.empty_like(ar_zeros_like_ar_ones.reshape(3,2))
ar_empty_line_zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [59]:
##>> eye
##N x N的单位矩阵
X=np.eye(3)
X

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [66]:
##>> full
Y=np.full((2,3),3.14)
Y

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])