In [ ]:
##daily0703
'''
1.bool索引：通常是利用对数组进行关系运算之后生成的bool数组，再对数组进行索引，选择符合条件的元素.

2.数组索引：又称为 fancy indexing 即以数组为下标，进行索引.


'''

In [2]:
import numpy as np
from np_print import print_np

In [4]:
##1.bool索引
##这个前面已经写过了，这里再简单展示一下

ar=np.arange(16).reshape(4,4)
print_np(ar)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 
shape: (4, 4)


In [5]:
ar[(ar>4)&(ar<11)]

array([ 5,  6,  7,  8,  9, 10])

In [6]:
##2.数组索引
ar[[0,2,3]]##即行索引： 第 1，3，4 行

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
ar[:,[0,2,3]]##按列索引

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15]])

In [8]:
br=np.arange(10)
ind=np.arange(2,6).reshape(2,2)
print_np(br)
print_np(ind)

[0 1 2 3 4 5 6 7 8 9] 
shape: (10,)
[[2 3]
 [4 5]] 
shape: (2, 2)


In [10]:
print_np(br[ind])##从br根据ind索引出来的数组，形状跟随ind，而不是br.

[[2 3]
 [4 5]] 
shape: (2, 2)


In [12]:
row=np.array([2,1,0])
col=np.array([3,2,1])
print_np(ar)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 
shape: (4, 4)


In [13]:
ar[row,col]

array([11,  6,  1])

In [14]:
ar[row[:,np.newaxis],col]

array([[11, 10,  9],
       [ 7,  6,  5],
       [ 3,  2,  1]])

In [16]:
##等同于：
ar[:3,1:].ravel()[::-1].reshape(3,3)

array([[11, 10,  9],
       [ 7,  6,  5],
       [ 3,  2,  1]])

In [22]:
##bool索引+数组索引
ar%2==0

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [23]:
np.all(ar%2==0,axis=0)

array([ True, False,  True, False])

In [24]:
ar[row[:,np.newaxis],np.all(ar%2==0,axis=0)]
##可以看出数组索引用于逆序选择子集时，很方便

array([[ 8, 10],
       [ 4,  6],
       [ 0,  2]])