In [ ]:
##daily0625
'''
一.向量与标量之间的基础6则运算
+：对应函数np.add
-：对应函数np.subtract
-(取负)：对应函数np.negative
*：对应函数np.multiply
/：对应函数np.divide
//：取整（地板除法），对应np.floor_divide
%：求余（取模），对应np.mod

以上对于向量的运算符号，实际是运算符的重载，最终调用对应的函数.

绝对值：np.abs

二.三角和反三角函数
np.sin
np.cos
np.tan
np.arcsin
np.arccos
np.arctan

三.指数和对数函数
1.指数函数：
np.exp(A)：    对A内元素x施以e^x计算. np.expm1对于非常小的输入值，可以保持较高的精度.
np.exp2(A)：   对A内元素x施以2^x计算.
np.power(n,A)：对A内元素x施以x^n计算.

2.对数函数
np.log(A)：    对A内元素x施以自然对数计算. np.log1p对于非常小的输入值，可以保持较高的精度.
np.log2(A)：   对A内元素x施以2为底的对数计算.
np.log10(A)：  对A内元素x施以10为底的对数计算.


四.一些高级特性
1.指定输出：所有通用函数可以通过out参数来指定计算结果的存放位置.
2.二元函数的聚合功能：

--累加与累积
np.add.reduce：     计算累加值，等同于np.sum
np.multiply.reduce：计算累积值，等同于np.prod

--每次累加与每次累积
np.add.accumulate：     计算每次累加值，等同于np.cumsum
np.multiply.accumulate：计算每次累积值，等同于np.cumprod

--向量外积
np.multiply.outer(x,y)

当然，向量内积是：
np.dot(x,y)

两个矩阵的哈达玛积用*表示：
X*Y, 这不是内积，注意区别.

'''

In [2]:
import numpy as np
##一.六则运算
ar=np.linspace(0,1,5)
ar

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [3]:
#:+
ar+1

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [4]:
#:-
ar-1

array([-1.  , -0.75, -0.5 , -0.25,  0.  ])

In [5]:
#:*
ar*5

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [6]:
#:/
ar/2

array([0.   , 0.125, 0.25 , 0.375, 0.5  ])

In [8]:
#://
ar*100//2

array([-0., 12., 25., 37., 50.])

In [10]:
#:% 求余取模
ar*500%2

array([0., 1., 0., 1., 0.])

In [11]:
#:绝对值
np.abs(ar-1)

array([1.  , 0.75, 0.5 , 0.25, 0.  ])

In [12]:
#：负数
-ar

array([-0.  , -0.25, -0.5 , -0.75, -1.  ])

In [19]:
##二.三角与反三角函数
#>三角函数
theta=np.linspace(0,np.pi/2,4)
theta

array([0.        , 0.52359878, 1.04719755, 1.57079633])

In [20]:
#:sin
np.sin(theta)

array([0.       , 0.5      , 0.8660254, 1.       ])

In [21]:
#:cos
np.cos(theta)

array([1.00000000e+00, 8.66025404e-01, 5.00000000e-01, 6.12323400e-17])

In [22]:
#:tan
np.tan(theta)

array([0.00000000e+00, 5.77350269e-01, 1.73205081e+00, 1.63312394e+16])

In [23]:
#>反三角函数
x=[-1,0,1]
#:arcsin
np.arcsin(x)

array([-1.57079633,  0.        ,  1.57079633])

In [24]:
#:arcos
np.arccos(x)

array([3.14159265, 1.57079633, 0.        ])

In [25]:
#:arctan
np.arctan(x)

array([-0.78539816,  0.        ,  0.78539816])

In [32]:
##三.指数和对数函数
#>指数函数
y=np.array([[0,1,2,3]])
np.exp(y)##e^y

array([[ 1.        ,  2.71828183,  7.3890561 , 20.08553692]])

In [33]:
np.exp2(y)##2^y

array([[1., 2., 4., 8.]])

In [34]:
np.power(3,y)##3^y

array([[ 1,  3,  9, 27]], dtype=int32)

In [46]:
#>对数函数

y=np.arange(4)
y=y+1
print(y)

[1 2 3 4]


In [47]:
#:以e为底
np.log(y)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [48]:
#:以2为底
np.log2(y)

array([0.       , 1.       , 1.5849625, 2.       ])

In [49]:
#:以10为底
np.log10(y)

array([0.        , 0.30103   , 0.47712125, 0.60205999])

In [50]:
##四.高级特性
#>1.指定输出

x=np.arange(5)
y=np.ones(5)
##所有的通用函数，可通过out指定输出
np.multiply(x,10,out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [52]:
#>2.聚合
x=np.arange(1,6)

#:求和
np.add.reduce(x)

15

In [53]:
##等同于np.sum
np.sum(x)

15

In [54]:
#:求积
np.multiply.reduce(x)

120

In [55]:
##等同于np.prod
np.prod(x)

120

In [56]:
#:每次累加
np.add.accumulate(x) == np.cumsum(x)

array([ True,  True,  True,  True,  True])

In [57]:
#:每次累积
np.multiply.accumulate(x) == np.cumprod(x)

array([ True,  True,  True,  True,  True])

In [58]:
#:外积
x1=np.ones(3)
y1=np.ones(3)

In [59]:
np.multiply.outer(x1,y1)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [60]:
#:内积
np.dot(x1,y1)

3.0