In [ ]:
##daily0620
'''
一.矩阵的向量化与向量的矩阵化
1.向量矩阵化：
--.reshape
--使用np.newaxis添加维数

2.矩阵向量化：
向量化分为行向量化与列向量化，前者在np中又称之为C序，后者成为F序.

行向量化:.ravel()不带参数的默认方法.该方法返回视图,如欲返回副本，应使用.flatten方法.
列向量化:.ravel('F')带'F'（Fotran）参数的方法.

二.矩阵的合并于拆分
1.合并：使用np.contenate，以及命名指定轴向版本的np.vstack和np.hstack
2.拆分：使用np.split，以及命名指定轴向版本的np.vsplit和np.hsplit

三.构造重复矩阵
使用.rpeat构造行或列重复的矩阵
使用np.tile方法构造整体重复的矩阵（地板砖）

'''

In [1]:
import numpy as np
from np_print import print_np

In [2]:
##一
##1.向量矩阵化
arr=np.arange(3)
print_np(arr)

[0 1 2] 
shape: (3,)


In [3]:
arr=arr[:,np.newaxis]
print_np(arr)

[[0]
 [1]
 [2]] 
shape: (3, 1)


In [4]:
arr.reshape(1,3)

array([[0, 1, 2]])

In [8]:
##2.向量矩阵化
##以多种方法创建2*3矩阵

##>>full方法
ar_full=np.full((2,3),3.14)
ar_full

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [9]:
##>>arange方法
ar_arange=np.arange(6).reshape(2,3)
ar_arange

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
##>>linespace方法
##均匀分布在1到20之间的6个元素
ar_ls=np.linspace(1,20,6).reshape(2,3)
ar_ls

array([[ 1. ,  4.8,  8.6],
       [12.4, 16.2, 20. ]])

In [25]:
##>>np.random.random方法
##0到1之间均匀分布的6个元素
ar_rr=np.random.random((2,3))
ar_rr

array([[0.45836343, 0.69893958, 0.74045921],
       [0.79981224, 0.11855863, 0.53037326]])

In [15]:
##>>np.random.randint方法
##随机分布在0到10之间的6个元素
ar_ri=np.random.randint(0,10,(2,3))
ar_ri

array([[9, 0, 6],
       [4, 0, 9]])

In [17]:
##>>np.random.norm方法
##均值为0方差为1的标准正态分布下的6个元素
ar_rn=np.random.normal(0,1,(2,3))
ar_rn

array([[ 0.55466516, -0.33598215, -1.1069012 ],
       [ 0.05468068,  2.10905965,  0.42954235]])

In [20]:
##>>np.random.randn方法
##默认均值为0方差为1的标准正态分布
ar_rsn=np.random.randn(2,3)
ar_rsn

array([[-0.16151236,  0.36001457, -0.58263336],
       [ 0.73653834, -1.28629569,  2.08310677]])

In [28]:
##把以上生成矩阵元素的方法总结一把：
'''
1.np.linspace类似于np.arange，生成一维数组.linspace可以指定范围与步长,np.arange相当于np.linspace的特化方法.
2.np.random.random(0到1之间的均匀分布)类似于np.random.randn(标准正态分布)，各自包含默认的分布类型，只需要指定矩阵的形状.
  注意random需要一个元组作为形状的输入，randn则不需要.
  
3.np.random.randint和np.random.normal:两者的参数类型一致：需指定参数确定分布，指定形状确定矩阵.

'''

##向量化
ar_arange.ravel()[1]=100##ravel返回的为视图

In [29]:
ar_arange

array([[  0, 100,   2],
       [  3,   4,   5]])

In [30]:
ar_arange.ravel('F')##以列为向量化方向

array([  0,   3, 100,   4,   2,   5])

In [31]:
ar_arange.ravel()##默认以行

array([  0, 100,   2,   3,   4,   5])

In [32]:
ar_arange.flatten()[1]=1000##flatten返回向量化副本

In [33]:
ar_arange

array([[  0, 100,   2],
       [  3,   4,   5]])

In [34]:
ar_arange.flatten('F')

array([  0,   3, 100,   4,   2,   5])

In [35]:
##二.矩阵的合并与拆分
##1.合并
ar_ar=ar_arange

In [38]:
np.concatenate([ar_ar,ar_ls])##默认沿0轴向合并

array([[  0. , 100. ,   2. ],
       [  3. ,   4. ,   5. ],
       [  1. ,   4.8,   8.6],
       [ 12.4,  16.2,  20. ]])

In [39]:
np.concatenate([ar_ar,ar_ls],axis=1)##沿着1轴合并

array([[  0. , 100. ,   2. ,   1. ,   4.8,   8.6],
       [  3. ,   4. ,   5. ,  12.4,  16.2,  20. ]])

In [44]:
##使用vstack于hstack
ar_v=np.vstack([ar_ar,ar_ls])
ar_v

array([[  0. , 100. ,   2. ],
       [  3. ,   4. ,   5. ],
       [  1. ,   4.8,   8.6],
       [ 12.4,  16.2,  20. ]])

In [45]:
ar_h=np.hstack([ar_ar,ar_ls])
ar_h

array([[  0. , 100. ,   2. ,   1. ,   4.8,   8.6],
       [  3. ,   4. ,   5. ,  12.4,  16.2,  20. ]])

In [46]:
##2.拆分
s1,s2,s3=np.split(ar_h[0],[2,4])##使用数组作为索引进行拆分，n个索引拆分为n+1段.

In [47]:
print(s1,s2,s3)

[  0. 100.] [2. 1.] [4.8 8.6]


In [50]:
v1,v2=np.vsplit(ar_v,[2])##按0轴进行拆分，拆分为行.
print(v1,'\n\n',v2)

[[  0. 100.   2.]
 [  3.   4.   5.]] 

 [[ 1.   4.8  8.6]
 [12.4 16.2 20. ]]


In [51]:
h1,h2,h3=np.hsplit(ar_h,[1,3])##按1轴进行拆分，拆分为列.
print(h1,'\n\n',h2,'\n\n',h3)

[[0.]
 [3.]] 

 [[100.   2.]
 [  4.   5.]] 

 [[ 1.   4.8  8.6]
 [12.4 16.2 20. ]]


In [52]:
##三.构造重复元素的矩阵
##按行按列重复：.repeat方法
v1

array([[  0., 100.,   2.],
       [  3.,   4.,   5.]])

In [56]:
v1.repeat([2,3],axis=0)##沿0轴进行重复：第一行重复2次，第二行重复3次

array([[  0., 100.,   2.],
       [  0., 100.,   2.],
       [  3.,   4.,   5.],
       [  3.,   4.,   5.],
       [  3.,   4.,   5.]])

In [57]:
v1##repeat返回的是副本，不影响原矩阵

array([[  0., 100.,   2.],
       [  3.,   4.,   5.]])

In [62]:
v1.repeat(2)##如果不指定轴向就开始重复，那么结果是先向量化再重复每个元素

array([  0.,   0., 100., 100.,   2.,   2.,   3.,   3.,   4.,   4.,   5.,
         5.])

In [67]:
v1.repeat([3,2,1],axis=1)##沿1轴进行重复，第一列重复3次，第二列重复2次，第三列重复1次

array([[  0.,   0.,   0., 100., 100.,   2.],
       [  3.,   3.,   3.,   4.,   4.,   5.]])

In [68]:
##整体进行重复：np.tile
##如果说.repeat是按行按列分解进行重复
##那么np.tile就是把矩阵视为整体进行重复
np.tile(v1,2)

array([[  0., 100.,   2.,   0., 100.,   2.],
       [  3.,   4.,   5.,   3.,   4.,   5.]])

In [70]:
np.tile(v1,(2,1))

array([[  0., 100.,   2.],
       [  3.,   4.,   5.],
       [  0., 100.,   2.],
       [  3.,   4.,   5.]])

In [71]:
np.tile(v1,(1,2))##类似于np.tile(v1,2)

array([[  0., 100.,   2.,   0., 100.,   2.],
       [  3.,   4.,   5.,   3.,   4.,   5.]])